pip install tensorflow
pip install pickle
pip install unicorn['standard']
pip install python-multipart
pip install fastapi
pip install opencv-python
pip install matplotlib
pip install scipy
pip install librosa