services:
  # A Docker web service
  - type: web
    name: fastapi-api
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py